[project]
name = "ussh"
version = "0.1.6"
description = ""
readme = "README.md"
requires-python = ">=3.9.1"
dependencies = [
    "click>=8.1.7",
    "tabulate>=0.9.0"
]

[project.scripts]
ussh = "src.main:cli"

[tool.setuptools]
packages = ["src", "src.commands"]
