[project]
name = "ussh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.1"
dependencies = [
    "click>=8.1.8",
    "tabulate>=0.9.0",
]

[project.scripts]
ussh = "src.main:cli"

[tool.setuptools]
packages = ["src", "src.commands"]
